version: "3.7"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:

  router:
    image: docker.io/library/nginx
    ports:
      - "44000:44000"
    volumes:
      - ./nginx_router.conf:/etc/nginx/nginx.conf:ro,Z
    restart: always
    depends_on:
      - commands
      - views
      - ui
    logging: *default-logging

  commands:
    image: "kevinrutherford/rookery-commands:latest"
    depends_on:
      - eventstore
    environment:
      - DEVELOPMENT_BEARER_TOKEN=${DEVELOPMENT_BEARER_TOKEN}
    restart: always
    tty: true
    logging: *default-logging

  views:
    image: "kevinrutherford/rookery-views:latest"
    depends_on:
      - eventstore
    environment:
      - USER_1_ID=${USER_1_ID}
      - USER_1_USERNAME=${USER_1_USERNAME}
      - USER_1_DISPLAYNAME=${USER_1_DISPLAYNAME}
      - USER_1_AVATAR_URL=${USER_1_AVATAR_URL}
      - USER_2_ID=${USER_2_ID}
      - USER_2_USERNAME=${USER_2_USERNAME}
      - USER_2_DISPLAYNAME=${USER_2_DISPLAYNAME}
      - USER_2_AVATAR_URL=${USER_2_AVATAR_URL}
      - USER_3_ID=${USER_3_ID}
      - USER_3_USERNAME=${USER_3_USERNAME}
      - USER_3_DISPLAYNAME=${USER_3_DISPLAYNAME}
      - USER_3_AVATAR_URL=${USER_3_AVATAR_URL}
      - USER_CRB_ID=${USER_CRB_ID}
      - USER_CRB_USERNAME=${USER_CRB_USERNAME}
      - USER_CRB_DISPLAYNAME=${USER_CRB_DISPLAYNAME}
      - USER_CRB_AVATAR_URL=${USER_CRB_AVATAR_URL}
    restart: always
    tty: true
    logging: *default-logging

  sagas:
    image: "kevinrutherford/rookery-sagas:latest"
    depends_on:
      - commands
      - views
    environment:
      - USER_CRB_ID=${USER_CRB_ID}
    restart: "no"
    tty: true
    logging: *default-logging

  ui:
    image: "kevinrutherford/rookery-ui:latest"
    depends_on:
      - commands
      - views
    environment:
      - USER_1_ID=${USER_1_ID}
      - USER_1_USERNAME=${USER_1_USERNAME}
      - USER_2_ID=${USER_2_ID}
      - USER_2_USERNAME=${USER_2_USERNAME}
      - USER_3_ID=${USER_3_ID}
      - USER_3_USERNAME=${USER_3_USERNAME}
    restart: always
    logging: *default-logging

  eventstore:
    image: eventstore/eventstore:lts
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:

