version: "3.7"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:
  proxy:
    image: docker.io/library/nginx
    ports:
      # actual and only port facing any connection from outside
      # Note, change the left number if port 1236 is already in use on your system
      # You could use port 80 if you won't use a reverse proxy
      - "{{ rookery_port }}:8536"
    volumes:
      - ./nginx_internal.conf:/etc/nginx/nginx.conf:ro,Z
      - ./proxy_params:/etc/nginx/proxy_params:ro,Z
    restart: always
    logging: *default-logging
    depends_on:
      - rookery-ui

  rookery:
    image: {{ rookery_docker_image }}
    hostname: rookery
    restart: always
    logging: *default-logging
    environment:
{% if rookery_env_vars is defined and rookery_env_vars|length > 0 %}
{% for item in rookery_env_vars %}
{% for key, value in item.items() %}
      - {{ key }}={{ value }}
{% endfor %}
{% endfor %}
{% endif %}
    volumes:
      - ./rookery.hjson:/config/config.hjson:Z

  rookery-ui:
    image: {{ rookery_docker_ui_image }}
    environment:
{% if rookeryui_env_vars is defined and rookeryui_env_vars|length > 0 %}
{% for item in rookeryui_env_vars %}
{% for key, value in item.items() %}
      - {{ key }}={{ value }}
{% endfor %}
{% endfor %}
{% endif %}
    volumes:
      - ./volumes/rookery-ui/extra_themes:/app/extra_themes
    depends_on:
      - rookery
    restart: always
    logging: *default-logging

