version: "3.7"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:
  router:
    image: docker.io/library/nginx
    ports:
      # actual and only port facing any connection from outside
      - "44000:44000"
    volumes:
      - ./nginx_internal.conf:/etc/nginx/nginx.conf:ro,Z
      - ./proxy_params:/etc/nginx/proxy_params:ro,Z
    restart: always
    logging: *default-logging
    links:
      - ui
    depends_on:
      - ui

  ui:
    image: "kevinrutherford/rookery-ui:latest"
    restart: always
    logging: *default-logging

